name:                mcprotocolgenerator
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/Rubixdarcy/mcprotocolgenerator#README
license:             MIT
author:              Darcy Ryan
maintainer:          darcy150@gmail.com
copyright:           2021 Darcy Ryan
category:            Minecraft
extra-source-files:
- README.md

dependencies:
  - base
  - aeson
  - vector
  - text
  - bytestring
  - split
  - unordered-containers
  - directory
  - casing
  - optparse-applicative
  - filepath

executables:
  mcprotocolgenerator:
    source-dirs:      src
    main:             Main.hs
