name:                mcprotocolgenerator
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/mcprotocolgenerator#readme
license:             PublicDomain
author:              Darcy Ryan
maintainer:          darcy150@gmail.com
copyright:           2018 Darcy Ryan
category:            Minecraft
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - vector
  - text
  - bytestring
  - split
  - unordered-containers
  - directory
  - casing

executables:
  mcprotocolgenerator:
    source-dirs:      src
    main:             Main.hs
